# Generated by Django 5.2.7 on 2025-10-30 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('TD', 'To_Do'), ('IN_PRGRS', 'In_Progress'), ('COMPTD', 'Completed')], default='TD', max_length=100)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MDIUM', 'Medium'), ('HIGH', 'High')], default='MDIUM', max_length=50)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
