# Generated by Django 5.2.7 on 2025-11-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskhero', '0005_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
